This is data only — no functions. Replace all remaining emojis with Bootstrap icons:
const providers = [
  {
    id: 1,
    name: "Mrs. Oyindamola",
    role: "Caterer & Baking Expert",
    category: "Catering",
    icon: "bi bi-cup-hot",
    avatarBg: "#e6f9ee",
    rating: 4.9,
    reviewCount: 247,
    jobs: 312,
    experienceYears: "5yrs",
    location: "Malete, Kwara State",
    locationKey: "Kwara",
    availability: "online",
    availText: "Available Now — Delivers Nationwide",
    tags: ["Baking", "Cooking", "Events Catering"],
    bio: "Certified master caterer with 5 years experience across Kwara State, delivering nationwide service. I specialise in baking, cooking and events catering — from small family occasions to large corporate events. Fast, honest and reliable.\n\nI work closely with every client to create menus that suit their budget and taste. No hidden charges, no surprises. Every dish is made fresh with quality ingredients.\n\nI deliver nationwide through trusted logistics partners and also offer home visits across Kwara State. Contact me for menu ideas, pricing and availability.",
    skills: ["Baking", "Cooking", "Events Catering", "Menu Planning", "Dietary Accommodations", "Food Delivery", "Nationwide Service", "Home Visits", "Corporate Catering", "Small Chops"],
    price: "₦Talk-Price",
    per: "/job",
    verified: true,
    experience: [
      { icon: "bi bi-cup-hot", title: "Master Caterer — Self Employed", desc: "Running her own catering business serving events of all sizes across Kwara State and nationwide delivery.", date: "2019 — Present · 5 years" },
      { icon: "bi bi-cake", title: "Pastry Chef — Kwara Cuisine", desc: "Specialised in baking and pastry work for events, weddings and corporate clients.", date: "2017 — 2019 · 2 years" },
      { icon: "bi bi-fire", title: "Cook — KWASU", desc: "Started career cooking for student events and local functions in Malete.", date: "2014 — 2017 · 3 years" },
    ],
    reviews: [
      { avatar: "bi bi-person-circle", name: "Hajia Bintu", date: "3 days ago · Ilorin, Kwara", stars: "★★★★★", text: "She catered my daughter's wedding and every single guest was raving about the food. The jollof rice alone was worth every naira. Professional, punctual and truly passionate about her craft.", tag: "Wedding Catering" },
      { avatar: "bi bi-person-circle", name: "Mr. Raheem", date: "2 weeks ago · Offa, Kwara", stars: "★★★★★", text: "Ordered her small chops for our company event. 200 guests and not a single complaint about the food. She delivered on time and everything was fresh and delicious.", tag: "Corporate Event" },
      { avatar: "bi bi-person-circle", name: "Mrs. Pulch", date: "1 month ago · Malete", stars: "★★★★★", text: "Best caterer in Kwara, full stop. Her chin-chin and puff puff are absolutely out of this world. I order from her every month for family gatherings.", tag: "Baking" },
    ],
    gallery: ["bi bi-cup-hot", "bi bi-cake", "bi bi-fire", "bi bi-basket", "bi bi-box", "bi bi-stars"],
  },

  {
    id: 2,
    name: "Miss Gift",
    role: "Counselor & Life Coach",
    category: "Tutoring",
    icon: "bi bi-book",
    avatarBg: "#fff8ec",
    rating: 5.0,
    reviewCount: 183,
    jobs: 201,
    experienceYears: "4yrs",
    location: "Warri, Delta State",
    locationKey: "Warri",
    availability: "online",
    availText: "Available Now",
    tags: ["Psychology", "Mentoring", "Career Guidance"],
    bio: "Top-rated life coach and counselor helping people make confident life decisions. Over 90% of my clients report significant improvement in their confidence and career clarity within 3 sessions.\n\nI specialise in career counseling, life coaching and mentoring — whether you're a student choosing a university, a fresh graduate entering the job market, or someone at a crossroads in their career.\n\nBased in Warri but I work with clients across Delta State and nationwide through online sessions. I create a safe, non-judgmental space where you can explore your thoughts freely and develop clear, actionable plans.",
    skills: ["Career Counseling", "Life Coaching", "WAEC Guidance", "University Choice", "Mental Health Support", "Confidence Building", "Study Skills", "Goal Setting", "Home Visits", "Online Sessions"],
    price: "₦Fixed-Price",
    per: "/session",
    verified: true,
    experience: [
      { icon: "bi bi-lightbulb", title: "Life Coach & Counselor — Self Employed", desc: "Running independent counseling and life coaching practice, serving clients across Delta State and online nationwide.", date: "2020 — Present · 4 years" },
      { icon: "bi bi-book", title: "Academic Counselor — Warri Secondary School", desc: "Guided students through WAEC preparation, university applications and career choices.", date: "2018 — 2020 · 2 years" },
      { icon: "bi bi-mortarboard", title: "Volunteer Mentor — Delta State Youth Centre", desc: "Mentored young people on career development and goal setting.", date: "2016 — 2018 · 2 years" },
    ],
    reviews: [
      { avatar: "bi bi-person-circle", name: "Chisom A.", date: "1 week ago · Warri", stars: "★★★★★", text: "Miss Gift changed my life literally. I was confused about my career path and after just 2 sessions with her I had complete clarity. She listens without judgment and gives practical advice that actually works.", tag: "Career Counseling" },
      { avatar: "bi bi-person-circle", name: "Emeka's Dad", date: "3 weeks ago · Asaba", stars: "★★★★★", text: "Hired her to counsel my son before JAMB and university choice. He went from a D student to getting admitted into his first choice school. She has a gift for bringing out the best in young people.", tag: "Academic Guidance" },
      { avatar: "bi bi-person-circle", name: "Blessing O.", date: "2 months ago · Lagos", stars: "★★★★★", text: "Online session was excellent. She helped me navigate a very difficult career transition and I'm now 6 months into my dream job. Worth every kobo.", tag: "Life Coaching" },
    ],
    gallery: ["bi bi-book", "bi bi-lightbulb", "bi bi-bullseye", "bi bi-stars", "bi bi-award", "bi bi-check-circle"],
  },

  {
    id: 3,
    name: "Mr. Fatai",
    role: "Auto Mechanic",
    category: "Auto Mechanic",
    icon: "bi bi-car-front",
    avatarBg: "#eef3ff",
    rating: 4.8,
    reviewCount: 312,
    jobs: 405,
    experienceYears: "37yrs",
    location: "Ikeja, Lagos",
    locationKey: "Lagos",
    availability: "busy",
    availText: "Busy — replies soon",
    tags: ["Toyota", "Honda", "Mobile Service"],
    bio: "Mobile mechanic with 37 years of experience serving Ikeja and surrounding areas. I come to you — no need to tow your car anywhere. I specialise in Japanese cars but handle all brands with equal expertise.\n\nI am known for transparent pricing and honest assessment. I will never tell you something is wrong with your car if it isn't. No hidden charges, ever.\n\nWith 37 years in the trade I have seen and fixed every kind of problem. I detect faults accurately the first time and fix them right the first time. Emergency repairs available with fast response times.",
    skills: ["Mobile Mechanic", "Toyota Specialist", "Honda Specialist", "All Brands", "Honest Diagnosis", "Transparent Pricing", "Emergency Repairs", "Engine Repair", "Brake System", "Electrical Faults"],
    price: "₦Talk-Price",
    per: "/job",
    verified: true,
    experience: [
      { icon: "bi bi-car-front", title: "Senior Mobile Mechanic — Self Employed", desc: "Running independent mobile mechanic service across Ikeja and Lagos, specialising in Japanese car brands.", date: "2010 — Present · 14 years" },
      { icon: "bi bi-tools", title: "Lead Mechanic — Toyota Nigeria Service Centre", desc: "Senior mechanic handling diagnostics, servicing and complex repairs for Toyota vehicles.", date: "2000 — 2010 · 10 years" },
      { icon: "bi bi-mortarboard", title: "Mechanic — Mushin Auto Workshop", desc: "Trained under one of Lagos' most respected master mechanics. Learned the full trade from diagnostics to fabrication.", date: "1987 — 2000 · 13 years" },
    ],
    reviews: [
      { avatar: "bi bi-person-circle", name: "Tunde A.", date: "1 week ago · Ikeja", stars: "★★★★★", text: "Fixed my Honda Accord in 2 hours. Honest pricing and no surprises. He told me exactly what was wrong and showed me the problem before fixing it. That kind of transparency is rare.", tag: "Engine Repair" },
      { avatar: "bi bi-person-circle", name: "Mrs. Bello", date: "2 weeks ago · Ogba", stars: "★★★★★", text: "My car broke down on Third Mainland Bridge and he came to me within 30 minutes. Fixed it on the spot. Absolute legend. Saved my whole day.", tag: "Emergency Repair" },
      { avatar: "bi bi-person-circle", name: "Alhaji Musa", date: "1 month ago · Maryland", stars: "★★★★★", text: "Been using Mr. Fatai for 8 years now. He has never once overcharged me or invented a problem that wasn't there. In Lagos that is extremely rare. My family's mechanic for life.", tag: "Full Servicing" },
    ],
    gallery: ["bi bi-car-front", "bi bi-tools", "bi bi-wrench", "bi bi-gear", "bi bi-speedometer", "bi bi-trophy"],
  },

  {
    id: 4,
    name: "Miss Haleemah Amope",
    role: "Content Creator",
    category: "ContentCreator",
    icon: "bi bi-camera",
    avatarBg: "#ffeef3",
    rating: 4.7,
    reviewCount: 98,
    jobs: 120,
    experienceYears: "3yrs",
    location: "Ikeja, Lagos",
    locationKey: "Lagos",
    availability: "online",
    availText: "Available Now",
    tags: ["Social Media", "Ads", "Video"],
    bio: "Creative content specialist helping small businesses grow their online presence end-to-end. I handle photography, video editing, social media strategy, ad creation and branding — all under one roof so you don't need to hire multiple people.\n\nI have helped over 50 small businesses in Lagos grow their customer base through effective content. My work is clean, modern and tailored to your brand voice.\n\nBased in Ikeja but I work with clients across Lagos and remotely nationwide. I take the stress of your online presence off your hands completely.",
    skills: ["Photography", "Video Editing", "Social Media Strategy", "Ad Creation", "Branding", "Online Growth", "Small Business Support", "Instagram Marketing", "TikTok Content", "Product Photography"],
    price: "₦Talk-Price",
    per: "/project",
    verified: true,
    experience: [
      { icon: "bi bi-camera", title: "Content Creator & Social Media Strategist — Self Employed", desc: "Creating content and managing social media for small businesses across Lagos.", date: "2021 — Present · 3 years" },
      { icon: "bi bi-camera-video", title: "Video Editor — MediaHouse Lagos", desc: "Edited promotional videos, brand content and social media reels for local and international clients.", date: "2020 — 2021 · 1 year" },
      { icon: "bi bi-mortarboard", title: "Photography Intern — Clicks Studio", desc: "Trained in professional photography, lighting and post-production editing.", date: "2019 — 2020 · 1 year" },
    ],
    reviews: [
      { avatar: "bi bi-person-circle", name: "Adeola B.", date: "5 days ago · Lekki", stars: "★★★★★", text: "She handled our restaurant's Instagram for 2 months and our followers grew from 400 to 4,200. The content quality is stunning and she captures the essence of our brand perfectly.", tag: "Social Media Management" },
      { avatar: "bi bi-person-circle", name: "Tunde Fabrics", date: "3 weeks ago · Ikeja", stars: "★★★★★", text: "Product photography was incredible. My WhatsApp catalogue now looks like a proper brand. Customers comment on the quality of my photos all the time now.", tag: "Product Photography" },
      { avatar: "bi bi-person-circle", name: "Mama Chichi", date: "2 months ago · Surulere", stars: "★★★★★", text: "She created a TikTok video for my food business that got 45,000 views. I had to close orders for 2 weeks because I was overwhelmed. Best investment I ever made.", tag: "Video Content" },
    ],
    gallery: ["bi bi-camera", "bi bi-camera-video", "bi bi-phone", "bi bi-palette", "bi bi-graph-up", "bi bi-stars"],
  },

  {
    id: 5,
    name: "Alhaji Suleiman",
    role: "Electrical Engineer",
    category: "Electrical",
    icon: "bi bi-lightning-charge",
    avatarBg: "#fffbec",
    rating: 4.9,
    reviewCount: 156,
    jobs: 198,
    experienceYears: "6yrs",
    location: "Apapa, Lagos",
    locationKey: "Lagos",
    availability: "online",
    availText: "Available Now",
    tags: ["Solar", "Generator", "Wiring"],
    bio: "Licensed electrician specialising in solar panel installations, generator servicing and full electrical wiring for residential and commercial properties. Available 24/7 for emergencies across Lagos.\n\nWith 6 years of hands-on experience, I have completed over 198 electrical projects without a single safety incident. I follow strict electrical safety standards on every job.\n\nBased in Apapa but I serve the entire Lagos state. Fast response times for emergencies. All work comes with a service guarantee.",
    skills: ["Solar Panel Installation", "Generator Servicing", "Electrical Wiring", "Emergency Repairs", "24/7 Availability", "Residential Projects", "Commercial Projects", "Safety Compliance", "Inverter Installation", "Meter Installation"],
    price: "₦Talk-Price",
    per: "/job",
    verified: true,
    experience: [
      { icon: "bi bi-lightning-charge", title: "Licensed Electrician — Self Employed", desc: "Handling residential and commercial electrical projects across Lagos. Specialising in solar and generator systems.", date: "2018 — Present · 6 years" },
      { icon: "bi bi-sun", title: "Solar Technician — GreenPower Lagos", desc: "Installed and maintained solar power systems for homes and businesses across Lagos State.", date: "2016 — 2018 · 2 years" },
      { icon: "bi bi-mortarboard", title: "Electrical Apprentice — Apapa Technical Workshop", desc: "Completed full electrical engineering apprenticeship under licensed master electrician.", date: "2013 — 2016 · 3 years" },
    ],
    reviews: [
      { avatar: "bi bi-person-circle", name: "Mrs. Fashola", date: "2 days ago · Victoria Island", stars: "★★★★★", text: "He installed a complete solar system in our 4-bedroom house in one day. The work is neat, professional and the system has been running perfectly for 3 months.", tag: "Solar Installation" },
      { avatar: "bi bi-person-circle", name: "Oga Biodun", date: "2 weeks ago · Apapa", stars: "★★★★★", text: "Called him at 11pm for an electrical emergency and he arrived within 45 minutes. Fixed the fault, explained everything clearly, and the charge was very fair.", tag: "Emergency Repair" },
      { avatar: "bi bi-person-circle", name: "Manager, Crest Hotel", date: "1 month ago · Ikeja", stars: "★★★★★", text: "Rewired our entire hotel floor during renovation. Zero disruptions to operations, completed ahead of schedule and the work passed inspection first time.", tag: "Commercial Wiring" },
    ],
    gallery: ["bi bi-lightning-charge", "bi bi-sun", "bi bi-plug", "bi bi-lightbulb", "bi bi-house", "bi bi-battery-charging"],
  },

  {
    id: 6,
    name: "Mr. Aminu Yusuf",
    role: "Professional Cleaner",
    category: "Cleaning",
    icon: "bi bi-stars",
    avatarBg: "#eef3ff",
    rating: 4.6,
    reviewCount: 74,
    jobs: 89,
    experienceYears: "2yrs",
    location: "Lagos",
    locationKey: "Lagos",
    availability: "away",
    availText: "Away — back tomorrow",
    tags: ["Deep Clean", "Post-Construction", "Office"],
    bio: "Professional cleaning service with my own trained team and equipment. We handle residential homes, offices and post-construction sites across Lagos. Fast, thorough and affordable.\n\nWe use professional-grade cleaning products and bring all equipment — you don't need to provide anything. Every job is done to the highest standard with attention to detail.\n\nWe also offer eco-friendly cleaning options for clients who prefer it. Flexible scheduling available including weekends.",
    skills: ["Deep Cleaning", "Office Cleaning", "Post-Construction Cleaning", "Eco-Friendly Products", "Team Service", "Residential Cleaning", "Move-In Cleaning", "Move-Out Cleaning", "Window Cleaning", "Carpet Cleaning"],
    price: "₦Talk-Price",
    per: "/session",
    verified: true,
    experience: [
      { icon: "bi bi-stars", title: "Professional Cleaning Service — Self Employed", desc: "Running a team-based cleaning service for homes, offices and post-construction sites across Lagos.", date: "2022 — Present · 2 years" },
      { icon: "bi bi-building", title: "Office Cleaner — CleanPro Lagos", desc: "Managed daily and deep cleaning operations for commercial office spaces in Lagos Island.", date: "2020 — 2022 · 2 years" },
    ],
    reviews: [
      { avatar: "bi bi-person-circle", name: "Mrs. Okonkwo", date: "1 week ago · Lekki Phase 1", stars: "★★★★★", text: "They deep cleaned my 3-bedroom apartment before I moved in. The place was sparkling. They got to corners and surfaces I didn't even think to mention. Very thorough team.", tag: "Deep Cleaning" },
      { avatar: "bi bi-person-circle", name: "Site Manager, Magodo Project", date: "3 weeks ago · Magodo", stars: "★★★★★", text: "Post-construction cleaning for a 6-unit building. They handled everything professionally, removed all construction debris and dust. Site was ready for handover the same day.", tag: "Post-Construction" },
      { avatar: "bi bi-person-circle", name: "Admin Manager, Lagos Office", date: "2 months ago · Victoria Island", stars: "★★★★★", text: "We use them every week for our office. Always punctual, always thorough and the team is professional and respectful. Great value for the quality of service.", tag: "Office Cleaning" },
    ],
    gallery: ["bi bi-stars", "bi bi-house", "bi bi-building", "bi bi-droplet", "bi bi-shield-check", "bi bi-award"],
  },

  {
    id: 7,
    name: "Mr. Obasola S.O",
    role: "Chief Mechanic",
    category: "Auto Mechanic",
    icon: "bi bi-wrench",
    avatarBg: "#e6f9ee",
    rating: 4.9,
    reviewCount: 247,
    jobs: 300,
    experienceYears: "8yrs",
    location: "Agege, Lagos",
    locationKey: "Lagos",
    availability: "online",
    availText: "Available Now",
    tags: ["Diagnostics", "Fabrication", "All Brands"],
    bio: "Chief mechanic with 8 years of experience handling all vehicle types. Known across Lagos for honest assessment and zero hidden charges. Workshop based in Yaba.\n\nI handle everything from computer diagnostics to metal fabrication. If your car has a problem I will find it — accurately and quickly. I specialise in all vehicle brands with a focus on quality workmanship and total transparency.\n\nWorkshop based in Yaba but I can come to you anywhere in Lagos for mobile repairs. Emergency repairs available with fast response times.",
    skills: ["Vehicle Diagnostics", "Metal Fabrication", "All Vehicle Brands", "Computer Diagnostics", "Engine Overhaul", "Gearbox Repair", "Suspension Work", "Emergency Repairs", "Mobile Service", "Workshop Service"],
    price: "₦Talk-Price",
    per: "/job",
    verified: true,
    experience: [
      { icon: "bi bi-wrench", title: "Chief Mechanic — Obasola Auto Workshop", desc: "Owns and operates a full-service auto workshop in Yaba. Handles all vehicle brands with a team of trained mechanics.", date: "2016 — Present · 8 years" },
      { icon: "bi bi-car-front", title: "Senior Mechanic — Coscharis Motors", desc: "Worked as senior mechanic for one of Nigeria's largest car dealerships handling premium vehicle brands.", date: "2012 — 2016 · 4 years" },
      { icon: "bi bi-mortarboard", title: "Technical Trainee — NNPC Workshop", desc: "Completed advanced automotive engineering training at the NNPC technical workshop.", date: "2010 — 2012 · 2 years" },
    ],
    reviews: [
      { avatar: "bi bi-person-circle", name: "Barrister Okafor", date: "4 days ago · Yaba", stars: "★★★★★", text: "He diagnosed a fault that 3 other mechanics missed. Fixed it in 2 hours. The car has been running perfectly for 4 months since. His knowledge is exceptional.", tag: "Vehicle Diagnostics" },
      { avatar: "bi bi-person-circle", name: "Mrs. Adeyemi", date: "2 weeks ago · Agege", stars: "★★★★★", text: "Brought my car for full servicing and gearbox repair. The work was thorough, the price was fair and he called me with updates throughout the process.", tag: "Full Servicing" },
      { avatar: "bi bi-person-circle", name: "Alhaji Rasheed", date: "1 month ago · Surulere", stars: "★★★★★", text: "Been taking all my family's cars to him for 5 years. He has saved us hundreds of thousands of naira by giving honest assessments. A man of integrity.", tag: "General Repairs" },
    ],
    gallery: ["bi bi-wrench", "bi bi-car-front", "bi bi-gear", "bi bi-tools", "bi bi-speedometer", "bi bi-trophy"],
  },

  {
    id: 8,
    name: "Miss Pulchritude",
    role: "Tailor & Fashion Designer",
    category: "Tailoring",
    icon: "bi bi-scissors",
    avatarBg: "#ffeef3",
    rating: 4.8,
    reviewCount: 130,
    jobs: 160,
    experienceYears: "5yrs",
    location: "Ogun State",
    locationKey: "Ogun",
    availability: "busy",
    availText: "Busy — replies soon",
    tags: ["Native Wear", "English Style", "Alterations"],
    bio: "Fashion designer and tailor with 5 years of experience creating stunning native and English wear. Known for delivering exactly what the client envisions — sometimes even better.\n\nI work closely with each client from fabric selection to final fitting. Every stitch is done with care and precision. I never rush a job because quality is non-negotiable for me.\n\nI handle native agbada, babariga, aso-oke, English suits, dresses, alterations, bridal wear and corporate uniforms.",
    skills: ["Native Wear", "English Style", "Alterations", "Custom Designs", "Bridal Wear", "Men's Fashion", "Women's Fashion", "Corporate Uniforms", "Aso-Oke Styling", "Fabric Selection"],
    price: "₦Talk-Price",
    per: "/outfit",
    verified: true,
    experience: [
      { icon: "bi bi-scissors", title: "Fashion Designer — Pulchritude Styles", desc: "Running her own fashion design studio in Ogun State, creating custom native and English wear for clients across Nigeria.", date: "2019 — Present · 5 years" },
      { icon: "bi bi-bag", title: "Tailor — Elegance Fashion House", desc: "Worked as a senior tailor creating bespoke outfits for weddings, events and corporate clients.", date: "2017 — 2019 · 2 years" },
      { icon: "bi bi-mortarboard", title: "Fashion Design Trainee — Ogun Style Academy", desc: "Completed professional fashion design training with specialisation in native and contemporary styles.", date: "2015 — 2017 · 2 years" },
    ],
    reviews: [
      { avatar: "bi bi-person-circle", name: "Sis Folake", date: "1 week ago · Abeokuta", stars: "★★★★★", text: "She made my complete aso-ebi outfit for my sister's wedding and I received so many compliments I lost count. The fitting was perfect and she delivered 3 days before the deadline.", tag: "Native Wear" },
      { avatar: "bi bi-person-circle", name: "Mr. Adewale", date: "3 weeks ago · Lagos", stars: "★★★★★", text: "Had her make 3 agbada sets for my graduation. She captured my style perfectly even from just a description and photos. The embroidery work is stunning.", tag: "Men's Native Wear" },
      { avatar: "bi bi-person-circle", name: "Bride Tolani", date: "2 months ago · Ogun State", stars: "★★★★★", text: "She made my wedding dress and all bridesmaid outfits. The attention to detail was incredible. She made me feel so beautiful on my special day.", tag: "Bridal Wear" },
    ],
    gallery: ["bi bi-scissors", "bi bi-bag", "bi bi-palette", "bi bi-suit-heart", "bi bi-gem", "bi bi-stars"],
  },

  {
    id: 9,
    name: "Miss Marvelous O.",
    role: "Software Developer",
    category: "Programming",
    icon: "bi bi-laptop",
    avatarBg: "#eef3ff",
    rating: 4.7,
    reviewCount: 130,
    jobs: 47,
    experienceYears: "3yrs",
    location: "Ogun State",
    locationKey: "Ogun",
    availability: "busy",
    availText: "Busy — replies soon",
    tags: ["Web Dev", "Mobile App", "AI"],
    bio: "Full stack software developer with 3 years of hands-on experience building web and mobile applications for clients across Nigeria and internationally. I work remotely but offer physical meetings across Lagos and Ogun State.\n\nI specialise in React, Node.js, Python, Django and Flask. I build everything from simple business websites to complex web applications and system integrations.\n\nHonesty is my policy — I will never tell you something needs fixing if it doesn't. Every project comes with clear documentation and post-launch support.",
    skills: ["Full Stack Development", "React", "Node.js", "Python", "Django", "Flask", "PostgreSQL", "MySQL", "API Development", "AI & Machine Learning", "Mobile App Development", "UI/UX Design"],
    price: "₦Talk-Price",
    per: "/project",
    verified: true,
    experience: [
      { icon: "bi bi-laptop", title: "Full Stack Developer — TechHub Lagos", desc: "Building complex web applications and system integrations for clients across Africa and internationally.", date: "2023 — Present · 1 year" },
      { icon: "bi bi-globe", title: "Web Developer — Digital Solutions Agency", desc: "Developed and maintained multiple React and Node.js applications for local and international clients.", date: "2022 — 2023 · 1 year" },
      { icon: "bi bi-mortarboard", title: "Junior Developer — Freelance", desc: "Started career building websites and web applications for local businesses across Ogun and Lagos States.", date: "2021 — 2022 · 1 year" },
    ],
    reviews: [
      { avatar: "bi bi-person-circle", name: "Mrs. Asiwaju", date: "2 weeks ago · FCT, Abuja", stars: "★★★★★", text: "I know nothing about coding but she made the whole process easy and stress-free. She built our company website from scratch and it looks stunning.", tag: "Website Development" },
      { avatar: "bi bi-person-circle", name: "Alhaji Zeeno", date: "1 month ago · Surulere", stars: "★★★★★", text: "Fixed critical backend bugs that two other developers couldn't solve. She documented everything clearly and trained my team on the solution.", tag: "Backend Development" },
      { avatar: "bi bi-person-circle", name: "Anifowoshe", date: "2 months ago · Yaba", stars: "★★★★★", text: "She integrated a full payment system into our React app seamlessly. Responds fast, explains everything in plain English and her support after deployment is excellent.", tag: "API Integration" },
    ],
    gallery: ["bi bi-laptop", "bi bi-display", "bi bi-phone", "bi bi-gear", "bi bi-shield-lock", "bi bi-rocket"],
  },

  {
    id: 10,
    name: "Mallam Usman",
    role: "Plumber",
    category: "Plumbing",
    icon: "bi bi-tools",
    avatarBg: "#e6f9ee",
    rating: 4.7,
    reviewCount: 130,
    jobs: 47,
    experienceYears: "5yrs",
    location: "Kaduna State",
    locationKey: "Kaduna",
    availability: "busy",
    availText: "Busy — replies soon",
    tags: ["Plumbing", "Water Supply", "Drainage"],
    bio: "Experienced plumber with 5 years of experience in residential and commercial plumbing across Kaduna State. I specialise in water supply systems, drainage installation and all types of pipe repair works.\n\nI provide reliable, affordable and quality plumbing services. Every job is done neatly with minimal disruption to your home or business. Emergency plumbing services available with fast response.\n\nAll work comes with a satisfaction guarantee. If there's a problem after I leave, I come back and fix it at no extra charge.",
    skills: ["Pipe Installation", "Water Supply Systems", "Drainage Installation", "Emergency Repairs", "Leak Detection", "Bathroom Fitting", "Tank Installation", "Borehole Plumbing", "Commercial Plumbing", "Maintenance Service"],
    price: "₦Talk-Price",
    per: "/job",
    verified: true,
    experience: [
      { icon: "bi bi-tools", title: "Professional Plumber — Self Employed", desc: "Running independent plumbing service across Kaduna State for residential and commercial clients.", date: "2019 — Present · 5 years" },
      { icon: "bi bi-building", title: "Plumber — Kaduna Construction Company", desc: "Handled plumbing installations for new residential and commercial building projects.", date: "2017 — 2019 · 2 years" },
      { icon: "bi bi-mortarboard", title: "Plumbing Apprentice — Mallam Isa Workshop", desc: "Learned the full plumbing trade from a master plumber with over 20 years experience.", date: "2015 — 2017 · 2 years" },
    ],
    reviews: [
      { avatar: "bi bi-person-circle", name: "Mrs. Uche", date: "1 week ago · Kaduna", stars: "★★★★★", text: "He fixed a major pipe burst in my kitchen quickly and cleanly. No mess left behind, the repair is solid and the price was very fair.", tag: "Emergency Repair" },
      { avatar: "bi bi-person-circle", name: "Site Engineer, GRA Project", date: "1 month ago · Kaduna GRA", stars: "★★★★★", text: "He did all the plumbing for our 8-unit estate. Very professional, completed on schedule and the work passed inspection without any issues.", tag: "Commercial Plumbing" },
      { avatar: "bi bi-person-circle", name: "Mr. Danladi", date: "2 months ago · Tudun Wada", stars: "★★★★★", text: "My bathroom had a serious drainage problem for months. He fixed it permanently in one visit. Other plumbers kept patching it. He found the real cause and solved it properly.", tag: "Drainage Repair" },
    ],
    gallery: ["bi bi-tools", "bi bi-house", "bi bi-droplet", "bi bi-water", "bi bi-wrench-adjustable", "bi bi-gear"],
  },
];